# Generated by Django 4.2.6 on 2023-10-28 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chickencollector_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.CharField(choices=[('M', 'Morning'), ('A', 'Afternoon'), ('L', 'Late Afternoon')], default='M', max_length=1)),
                ('chicken', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chickencollector_app.chicken')),
            ],
        ),
    ]
