# Generated by Django 4.2.6 on 2023-10-28 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chickencollector_app', '0002_layings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Layings',
            new_name='Laying',
        ),
    ]
