# Generated by Django 4.2.6 on 2023-10-29 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chickencollector_app', '0003_rename_layings_laying'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='laying',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='laying',
            name='date',
            field=models.DateField(verbose_name='laying Date'),
        ),
    ]
