# Generated by Django 4.2.6 on 2023-10-29 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chickencollector_app', '0004_snack_alter_laying_options_alter_laying_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='chicken',
            name='snacks',
            field=models.ManyToManyField(to='chickencollector_app.snack'),
        ),
    ]
